Add callback for error handling when using async
fluent/fluent-logger-golang pull request #97
Opened 2021-09-23 15:18 UTC by ivan-valkov

This PR adds an optional callback that can be called when a message is sent when using async. The callback can be used to pass errors to the caller so that they can decide what to do with the dropped message. It can also be used for monitoring by adding metrics in the callback, like a simple prometheus counter that counts successful vs failed logs.

Related to #80

2021-09-24 06:20 UTC, tagomoris requested changes
LGTM.
Could you add a section about the new option `AsyncResultCallback` to README?

2021-09-24 10:27 UTC, ivan-valkov commented
> LGTM.
> Could you add a section about the new option `AsyncResultCallback` to README?

Thanks for the quick review. Yep, I added a section under `1.6.2`. Would it be possible to cut a `1.6.2` release after this is merged?

2021-09-25 12:06 UTC, tagomoris commented
@ivan-valkov Yeah, I will.
But I meant the options description in README.md like [this](https://github.com/fluent/fluent-logger-golang#forcestopasyncsend).

2021-09-26 11:16 UTC, ivan-valkov commented
@tagomoris oh sorry, I misunderstood this, my bad. I have added the option description in the README.md now.

2021-09-26 11:29 UTC, tagomoris approved these changes
LGTM!

2021-09-26 11:29 UTC, merged

2021-09-26 11:31 UTC, tagomoris commented
Merged!
And I tagged `v1.6.2`. Thanks for the contribution!